- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.23
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "exampleuser"
        password: "us3rp@ssw0rd"
        roles: "tomcat"
  pre_tasks:
  - name: Delete old repo
    ansible.builtin.file:
      path: /etc/yum.repos.d/rh-cloud-rhel8-eus.repo
      state: absent

  - name: run redhat subscription
    community.general.redhat_subscription:
      state: present
      username: "{{ rhn_user }}"
      password: "{{ rhn_pass }}"
      pool_ids: "{{ rhn_pool }}"
  roles:
    - role: zaxos.tomcat-ansible-role
