---
- name: playbook to subscribe rhel
  hosts: all
  tasks:
  - name: Delete old repo
    ansible.builtin.file:
      path: /etc/yum.repos.d/rh-cloud-rhel8-eus.repo
      state: absent

  - name: run redhat subscription
    community.general.redhat_subscription:
      state: present
      username: "{{ rhn_user }}"
      password: "{{ rhn_pass }}"
      pool_ids: "{{ rhn_pool }}"
